### ISSUE TITLE
Numpad Enter does not evaluate input

### ISSUE THREAD

**Issue by thurstylark** [alt-romes/programmer-calculator#24]
Return will evaluate the existing line, but Enter on the numpad prints a newline instead.

IMO, Replacing `get_input()` with readline will take care of this, as well as several other possible corner cases that might come up later.

**Comment by GuilhermeGPGil** [comment]
Hi thurstylark! First of all thank you so much for the feedback you have provided here and on the reddit post! 
As for the bug, me and romes are unable to recreate it. 
For us the numpad enter is working just fine.
If you have any idea as what happens when you press the numpad enter, or if you can fix it, please let us know.

**Comment by DevManu-de** [comment]
I have to agree with @GuilhermeGPGil. I cant recreate the problem either.

**Comment by alt-romes** [comment]
If this comes up again, I'll reopen the issue again later.
As of now we can't recreate this problem
