### ISSUE TITLE
history.c from #36

### ISSUE THREAD

**Issue by DevManu-de** [alt-romes/programmer-calculator#38]
@alt-romes I will improve the history.c as mentioned in #36.

**Comment by alt-romes** [comment]
@DevManu-de after you're done with `history.c`, we need to double check `add_number_to_history` since it uses `rr` and `rr` will no longer apply the global mask inside it.

Using `rr` forgetting that the result was being masked by `globalmask` was probably a mistake either way, but we'll have to review it.

**Comment by DevManu-de** [comment]
@alt-romes 

> browsehistory:
> document mode and/or call it something else (dir, delta, ...)
> searchHistory is currently hard-coded here (but possibly this should all go away in favor of readline's internal history)
> to help avoid this kind of thing, simply refuse to have any global variables - make everything local to main or similar

Should I try to implement readline and its history or should we keep the current input and history functions.

**Comment by DevManu-de** [comment]
For the 
> to help avoid this kind of thing, simply refuse to have any global variables - make everything local to main or similar

I have an Idea to reduce or even remove all the global variables.
What about making one structure that holds all the global variables and we just give the functions the apropiate pointer to that structure.

If you decide to implement it like I mentioned I will make a pr in the comming days.

**Comment by alt-romes** [comment]
From what I understood, `ncurses` and `readline` are not very compatible. Taking that into account, I don't think our history scrolling is too far from done (we need to implement the left and right arrows still), and I think we can handle the bugs that come along the way.

Regarding the global variables idea, I don't think it'll be cleaner, and since now we're already declaring the global variables in the respective header files instead of all over the place, I think the global variables are okay. However I feel like there might be some useless parameters somewhere we might have forgotten to remove and use a global variable there instead.

Thank you.
~romes
