### ISSUE TITLE
Linear git history

### ISSUE THREAD

**Issue by demo-exe** [alt-romes/programmer-calculator#86]
It should be considered to enforce linear history (squash + no merge commits) in PRs.
This really cleans up the history and removes any "fix123" comments which are created during review

**Comment by alt-romes** [comment]
Yes, a rebase over merge workflow is much better. I'll change the defaults to prohibit merging.

Regarding the squashing of commits into good individual commits -- this is a nice to have, but I don't want to block contributors on it -- even though we can advise them on MRs.
It's a great practice, but I like how this project has a low level of difficulty for contributors new to open source.

I'll appreciate if knowledgeable contributors do so, as do I, nonetheless.

For historic interest:
If you have a pull request with a commit which needs a tweak to address a review, I suggest amending the commit:
```
# after making changes, add changes to track
git add what_i_changed
git commit --amend
```

Afterwards, you can push to the remote branch the amended commit by pushing with lease:
```
git push --force-with-lease
```

`--force-with-lease` ensures that when we force-push, we're doing a force push over the repository as we last saw it. If, meanwhile, someone had added a new commit to the remote branch, `git push --force-with-lease` would fail because the state of the remote is not as we last saw it. Note that this might not be very important since commits on forks for MRs are usually only made by the fork's owner, but I see it as much better practice.

**Comment by alt-romes** [comment]
If you want to, feel free to re-open.

For now, as I said above, let's not enforce too strict restrictions.
As a maintainer I'll try to gently push good practices such as you described, and rebase and squash the MRs from our side.
